@R0
D=M//D=firstnumber
@R1
D=D-M//D=firstnumber-secondnumber
@OUTPUT_FIRST
D;JGT//ifD>0(firstisgreater)gotooutput_first
@R1
D=M//D=secondnumber
@OUTPUT_D
0;JMP//gotooutput_d
(OUTPUT_FIRST)
@R0
D=M//D=firstnumber
(OUTPUT_D)
@R2
M=D//M[2]=D(greatestnumber)
(INFINITE_LOOP)
@INFINITE_LOOP
0;JMP//infiniteloop
